# Response by message
### Placeholders for messages:
# - %player% - the name of the player that send the message/command
# - %adress% - the adress of the player that send the message/command
# - %displayname% - the displayname of the player that send the message/command (Set by EssentialsX or the most Nickname plugins)
# - %level% - the level of the player
# - %ping% - the ping of the player
messageEnable: false
message: "Please don't use inappropriate word"
command-message: "Please don't use inappropriate word in commands"

# Response by command

## Placeholders for command:
# - %player% - the name of the player that send the message/command

commandEnable: false
command: "warn %player% inappropriate word"

# Word list
words:
  - word
  - word
  - word
  - word
