name: NoBypass
author: OVERLOAD48, Larrox
version: '${project.version}'
main: com.arctic.NoBypass

commands:
  nobypass:
    description: Reload NoBypass config file
    permission: nobypass.reload
    permission-message: You can not use that command!
